INSTRUCTION_PATTERNS = [
    r"purpose(.*?)document[:：]",              # Purpose of the document: ...
    r"this document is intended(.*?)\.",      # This document is intended for...
    r"you must(.*?)\.",                       # You must comply with...
    r"please note(.*?)\.",                    # Please note that...
    r"it is important to note(.*?)\.",        # It is important to note that...
    r"the document contains(.*?)\.",          # The document contains information...
    r"this document(.*?)\.",                  # This document regulates...
    r"user manual",                           # Headers
    r"instruction manual",
    r"this document is intended for.*",
    r"it should be noted that.*",
]
