sweep_mode: grid

fixed:
  embedding:
    model: text-embedding-3-small

sweep:
  chunking.strategy: [by_paragraphs]
  chunking.chunk_size: [1500]
  chunking.overlap: [50, 100]
  retrieval.top_k: [5, 3]
  prompt.system_prompt_path:
    - prompts/strong.txt
  clean_context_instructions: [false]
  dialog_history: [0]
